var quoteArray= [
            {quote: "If you don't stick to your values when they are being tested, they're not values: they're hobbies.",
            source: "Jon Stewart"},
            {quote: "A flea can trouble a lion more than a lion can harm a flea.",
            source: "Kenyan proverb"},
            {quote: "A patient man willl eat ripe fruit.",
            source: "African proverb"},
            {quote: "When the mouth stumbles, it is worse than the foot.",
            source: "African proverb"},
            {quote: "When brothers fight to death, a stranger inherits their property.",
            source: "African proverb"},
            {quote: "If the sun claims that it has power over the moon, let it shine at night.",
            source: "African proverb"},
            {quote: "If you understand everything, you must be must be misinformed.",
            source: "Japanese proverb"},
            {quote: "Do not look where you fell, but where you slipped.",
            source: "African proverb"},
            {quote: "Sticks in a bundle are unbreakable.",
            source: "Kenyan proverb"},
            {quote: "A lie has many variations, the truth none.",
            source: "African proverb"},
            {quote: "A pearl is only a pearl once it's out of it's shell.",
            source: "African proverb"},
            {quote: "A wise man never knows all, only fools know everything.",
            source: "African proverb"},
            {quote: "To get lost is to learn the way.",
            source: "African proverb"},
            {quote: "It isn't the mountains ahead to climb that wears you down... it's the pebble in your shoe.",
            source: "Muhammad Ali"},
            {quote: "Don't dig up in doubt what you planted in faith.",
            source: "Unknown"},
            {quote: "Attachment to things drops away by itself when you no longer seek to find yourself in them.",
            source: "Eckhart Tolle"},
            {quote: "If you don't pull a problem out by its root you'll spend your life trimming its branches.",
            source: "Unknown"},
            {quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
            source: "Henry David Thoreau"},
            {quote: "The axe forgets, the tree remembers.",
            source: "African proverb"},
            {quote: "You only lose what you cling to.",
            source: "Buddha"},
            {quote: "Tension is you who you think you should be. Relaxation is who you are.",
            source: "Chinese proverb"},
            {quote: "Talk doesn't cook rice.",
            source: "Chinese proverb"},
            {quote: "To talk much and arrive nowhere is the same as climbing a tree to catch a fish.",
            source: "Chinese proverb"},
            {quote: "Put off for one day and ten days will pass by.",
            source: "Korean proverb"},
            {quote: "It's kind of fun to do the impossible.",
            source: "Walt Disney"},
            {quote: "Never mistake activity for achievement.",
            source: "John Wooden"},
               ];
